# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=200)),
                ('locLat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('locLong', models.DecimalField(decimal_places=20, max_digits=25)),
                ('pic', models.CharField(max_length=1000000)),
                ('Type', models.BooleanField()),
            ],
        ),
    ]
