<<<<<<< HEAD
# Generated by Django 2.0.2 on 2018-03-11 07:27
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 07:25
from __future__ import unicode_literals
>>>>>>> da50377dc2260c4a00e2fa7d9ba24dcecb631f50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
<<<<<<< HEAD
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
=======
                ('id', models.UUIDField(default=uuid.UUID('825b3e04-75e3-446f-8891-588a0169037b'), editable=False, primary_key=True, serialize=False)),
>>>>>>> da50377dc2260c4a00e2fa7d9ba24dcecb631f50
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=200)),
                ('locLat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('locLong', models.DecimalField(decimal_places=20, max_digits=25)),
                ('pic', models.CharField(max_length=1000000)),
                ('Type', models.BooleanField()),
            ],
        ),
    ]
