# Generated by Django 2.0.2 on 2018-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='avgRating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
