# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cucumber',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='review',
            name='spicy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='thickness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
