# Generated by Django 2.0.2 on 2018-03-11 07:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0002_vendor_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='avgCucumber',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avgSpicy',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avgThickness',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avgTime',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='a', max_length=30), blank=True, default=list, size=None),
        ),
    ]
