# Generated by Django 2.0.2 on 2018-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0002_auto_20180303_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='pic',
            field=models.CharField(max_length=1000000),
        ),
    ]
