# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0002_auto_20180311_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userID',
            field=models.UUIDField(default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='review',
            name='vendorID',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
