# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0002_auto_20180323_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userID',
            field=models.CharField(max_length=40),
        ),
    ]
