# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 01:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0002_auto_20180624_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suggestions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fiveStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fourStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='negativeReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='oneStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='positiveReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rankingScore',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='threeStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='twoStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='userID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
