# Generated by Django 2.0.2 on 2018-03-11 08:09

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0003_auto_20180311_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('spicy', models.IntegerField(default=0)),
                ('thickness', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=240)),
                ('vendorID', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('userID', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('reviews', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='a', max_length=30), blank=True, default=list, size=None)),
            ],
        ),
    ]
