# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 02:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0003_auto_20180323_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suggestions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
