# Generated by Django 2.0.2 on 2018-03-12 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0004_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9eec51ff-284b-4cec-b9e2-37df3945914e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
