# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 03:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0004_auto_20180311_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='a', max_length=50), blank=True, default=list, size=None),
        ),
    ]
