# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0005_auto_20180303_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Type',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
