# Generated by Django 2.0.2 on 2018-03-12 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0005_auto_20180311_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='testField',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
