# Generated by Django 2.0.2 on 2018-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0005_auto_20180303_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Type',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
