# Generated by Django 2.0.2 on 2018-03-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminRun', '0009_auto_20180311_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='testField',
        ),
    ]
