# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 23:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('spicy', models.IntegerField(blank=True, default=0, null=True)),
                ('thickness', models.IntegerField(blank=True, default=0, null=True)),
                ('channa', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=240)),
                ('vendorID', models.UUIDField(default=uuid.uuid1)),
                ('userID', models.CharField(max_length=40)),
                ('cucumber', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('suggestions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('reviews', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='a', max_length=50), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=200)),
                ('locLat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('locLong', models.DecimalField(decimal_places=20, max_digits=25)),
                ('pic', models.CharField(blank=True, max_length=1000000)),
                ('Type', models.BooleanField()),
                ('avgRating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('avgThickness', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avgTime', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avgCucumber', models.NullBooleanField()),
                ('avgSpicy', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avgChanna', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='a', max_length=50), blank=True, default=list, size=None)),
                ('positiveReviews', models.IntegerField(default=0)),
                ('negativeReviews', models.IntegerField(default=0)),
                ('oneStars', models.IntegerField(default=0)),
                ('twoStars', models.IntegerField(default=0)),
                ('threeStars', models.IntegerField(default=0)),
                ('fourStars', models.IntegerField(default=0)),
                ('fiveStars', models.IntegerField(default=0)),
                ('rankingScore', models.FloatField(default=0.0)),
                ('reportCount', models.IntegerField(default=0)),
                ('baseTrending', models.FloatField(default=0.0)),
            ],
        ),
    ]
