runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT doublesRun.wsgi

beta_settings:
    cloud_sql_instances: intense-dolphin-207823:us-east1:intense-dolphin-2

manual_scaling:
  instances: 1

runtime_config:
  python_version: 2